# Create namespace for the GitLab project named "go-like-boss-project"
kind: Namespace
apiVersion: v1
metadata:
  name: go-like-boss-project
---
# Create service account gitlab
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab
  namespace: go-like-boss-project
---
# Give edit role ServiceAccount 'gitlab' in namespace 'go-like-boss-project'
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: go-like-boss-project-rb
subjects:
- kind: ServiceAccount
  name: gitlab
  namespace: go-like-boss-project
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
